# KDE Neon
# Build Kara from release tag and publish .deb package

on:
  workflow_call:
    inputs:
      cache-file-path:
        required: true
        type: string
      version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-24.04
    container: invent-registry.kde.org/neon/docker-images/plasma:user
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/cache/restore@v4
        id: cache
        with:
          key: ${{ runner.os }}-v${{ inputs.version }}-${{ hashFiles(inputs.cache-file-path) }}
          path: ${{ inputs.cache-file-path }}
          fail-on-cache-miss: true
      - name: Update system
        run: sudo apt update -y && sudo apt dist-upgrade -y
      - name: Install extra build dependencies
        run: |
          sudo apt-get -y -qq install zstd cmake build-essential \
            qt6-declarative-dev extra-cmake-modules \
            qt6-base-dev libkf6i18n-dev libkf6service-dev \
            libkf6windowsystem-dev plasma-workspace-dev libkf6activities-dev \
            kwin-dev pkg-config libdrm-dev gettext
      - name: Extract release tarball
        run: |
          tar xvf ${{ inputs.cache-file-path }}
      - name: Build kara
        run: |
          cmake_opts=(
           -B kara-${{ inputs.version }}/build
           -S kara-${{ inputs.version }}
           -DBUILD_DEBS=ON
           )
           echo "${cmake_opts[@]}"
           cmake "${cmake_opts[@]}" && cmake --build kara-${{ inputs.version }}/build -j$(nproc) && echo "Build completed!" || echo "Build failed!" || exit 1
      - name: Build DEB
        id: step_build
        run: |
          cd kara-${{ inputs.version }}/build; cpack -G DEB -V -DCPACK_THREADS=$(nproc)
          artifact=$GITHUB_WORKSPACE/kara-${{ inputs.version }}/packages/kara-${{ inputs.version }}_amd64.deb
          publish_filename=kara-${{ inputs.version }}_kdeneon_amd64.deb
          echo "Moving file to $GITHUB_WORKSPACE/$publish_filename"
          mv $artifact $GITHUB_WORKSPACE/$publish_filename
          echo "ARTIFACT=$publish_filename" >> "$GITHUB_ENV"
          SHA256SUM=$(sha256sum $GITHUB_WORKSPACE/$publish_filename | awk '{ print $1 }')
          echo "ARTIFACT = $publish_filename | SHA256SUM = $SHA256SUM"
          echo "SHA256SUM=$SHA256SUM" >> "$GITHUB_ENV"
      - name: Publish DEB
        if: ${{ env.SHA256SUM != '' }}
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
          retention-days: 1
